### ISSUE TITLE
I try make script for generate russian inn codes. Can't use  faker-russian gem

### ISSUE THREAD

**Issue by ovcharenkodi** [asiniy/faker-russian#7]
Shell out:

inn_generetor git:(develop) ✗ ruby -v
ruby 2.2.0p0 (2014-12-25 revision 49005) **[x86_64-darwin14]**
inn_generetor git:(develop) ✗ gem list | grep faker
faker (1.4.3)
faker-russian (0.0.6)
➜  inn_generetor git:(develop) ✗ irb
2.2.0 :001 > require 'faker'
 => true 
2.2.0 :002 > Faker::Name.name
 => "Kylee Paucek" 
2.2.0 :003 > require 'faker-russian'
LoadError: cannot load such file -- faker-russian
	from /Users/dmitry/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/dmitry/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from (irb):3
	from /Users/dmitry/.rvm/rubies/ruby-2.2.0/bin/irb:11:in `<main>'
2.2.0 :004

**Comment by asiniy** [comment]
Duplication of https://github.com/asiniy/faker-russian/issues/6
